### ISSUE TITLE
RuntimeError: Failed to install dependency package.

### ISSUE THREAD

**Issue by dzc0d3r** [beeware/beeware.github.io#387]
I'm following the instructions as described in the `README.rst` file
so i created a virtual environment venv and choose python2 as the python interpreter
i activated the virtual environment and install lektor via `pip install lektor ` , but when i run `lektor server` am getting this error **`RuntimeError: Failed to install dependency package.`** 

**i'm on xubuntu 18.04 machine
using python2 and virtualenv**

and this is the full traceback : 
```
Updating packages in /home/m4dc0d3r/.cache/lektor/packages/040fcb00f7af41ad65f95162fc80b155 for project
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement lektor-atom==0.3 (from versions: 0.1, 0.2)
ERROR: No matching distribution found for lektor-atom==0.3
Traceback (most recent call last):
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/bin/lektor", line 8, in <module>
    sys.exit(main())
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/lektor/cli.py", line 627, in main
    cli.main(args=args, prog_name=name)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/lektor/cli.py", line 380, in server_cmd
    ctx.load_plugins()
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/lektor/cli.py", line 130, in load_plugins
    load_packages(self.get_env(), reinstall=reinstall)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/lektor/packages.py", line 306, in load_packages
    refresh=reinstall)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/lektor/packages.py", line 276, in update_cache
    download_and_install_package(package_root, package, version)
  File "/home/m4dc0d3r/Desktop/PROJECTS/beeware.github.io/venv/local/lib/python2.7/site-packages/lektor/packages.py", line 105, in download_and_install_package
    raise RuntimeError('Failed to install dependency package.')
RuntimeError: Failed to install dependency package.

```

**Comment by freakboy3742** [comment]
Thanks for the report; the README wasn't updated when we moved to Python 3 by default. Sorry for the confusion; if you try again with Python 3, you should have more luck.

**Comment by dzc0d3r** [comment]
i will try again with python3
